##### 1: Load packages --------------------------------------------------------
# devtools::install_github("moamiristat/grocerycart")
library(grocerycart)
library(dplyr)
library(lubridate)
library(ggplot2)
library(arules)

blue_palette <- c("#99D8EB", "#81C3D7", "#62A7C1", "#3A7CA5", 
                  "#285F80", "#16425B", "#0C2C3E", "#051E2C")

##### 2: Load data ------------------------------------------------------------
# Availbale datasets in package
# data(package = "grocerycart")
# ?customer_db_funmart

# 4,996 customers
data("customer_db_funmart")

# 12,000 orders
data("order_db_funmart")

# 144,159 line items
data("basket_db_funmart")

# Grocery: join tables
grocery <- 
  basket_db_funmart %>% 
    group_by(basket_id, order_id) %>% 
    summarise(cost = sum(price)) %>% 
    ungroup() %>% 
    inner_join(order_db_funmart, by = "order_id") %>% 
    inner_join(customer_db_funmart, by = "customer_id")

##### 3: General analysis -----------------------------------------------------
# Order frequency (3 customers ordered 9 times)
grocery_freq <- 
  grocery %>% 
    count(customer_id, name = "orders") %>% 
    count(orders, name = "customers")

grocery_freq %>% 
  ggplot(aes(x = orders, y = customers)) + 
  geom_col(colour = "grey", fill = blue_palette[4], alpha = .6) + 
  labs(x = "Customers", y = "Orders", 
       title = ("Order Freqeuncy"), 
       subtitle = "Example: 9 customers ordered 3 times") + 
  geom_text(aes(label = customers, vjust = -.2)) + 
  scale_x_continuous(breaks = 1:max(grocery_freq$customers)) + 
  hrbrthemes::theme_ipsum(grid = FALSE)

# Average order value
grocery %>% 
  summarise(avg_price = mean(cost), num_orders = n(), 
            num_customers = n_distinct(customer_id))

# Create grocery buckets based on width or number of buckets
bucket_width <- 100
bucket_num <- 5
grocery_buckets <- function(width = NULL, n = NULL) {
  if(is.null(width) && is.null(n) || !is.null(width) && !is.null(n)) {
    cat(crayon::red("Specify exactly one of width and n\n"))
  }
  
  grocery %>% 
    group_by(customer_name) %>% 
    summarise(total_spent = sum(cost)) %>% 
    mutate(spent_bucket = cut_interval(total_spent, 
                                       length = width, 
                                       n = n, 
                                       right = "FALSE")) %>% 
    count(spent_bucket, name = "num_orders")
}

grocery_buckets(width = 100) %>% 
  ggplot(aes(x = spent_bucket, y = num_orders)) + 
  geom_segment(aes(x = spent_bucket, xend = spent_bucket, y = 0, yend = num_orders),
               color = blue_palette[4], lwd = .25, lty = 2, alpha = .6) + 
  geom_point(size = 14, pch = 21, bg = blue_palette[3], col = blue_palette[1]) + 
  labs(x = "Price Range", y = "Baskets", 
       title = ("Basket Price Range"), 
       subtitle = "Example: 1521 orders had a value b/w 100 to 200") + 
  geom_text(aes(label = num_orders, size = 3), color = "white", fontface = "bold") + 
  hrbrthemes::theme_ipsum(grid = FALSE) + 
  scale_x_discrete(labels = function(x) stringr::str_replace(x, ",", "-") %>% 
                     stringr::str_remove_all("[\\(\\)\\[\\]]")) + 
  theme(legend.position = "none")

# Product distribution in baskets (draw average line)
basket_db_funmart %>% 
  count(product, name = "baskets") %>% 
  mutate(basket_perc = baskets / sum(baskets)) %>% 
  ggplot(aes(x = 1:200, y = basket_perc)) + 
  geom_point()

# Revenue generated by products (Nikai Air Fryer 3.2L generated 10% of revenue)
plotly::ggplotly(
  p = 
    basket_db_funmart %>% 
      group_by(product) %>% 
      summarise(revenue = sum(price), baskets = n()) %>% 
      mutate(revenue_perc = revenue / sum(revenue), 
             baskets_perc = baskets / sum(baskets)) %>% 
      #slice_max(n = 10, order_by = spent_perc) %>% 
      ggplot(aes(x = baskets_perc, y = revenue_perc)) + 
      geom_point(color = blue_palette[5], 
                 aes(
                   text = stringr::str_glue(
                     "Product: {product}
                     Revenue: ￡{scales::comma(round(revenue))} ({round(revenue_perc *100, 4)}%)
                     Basket: {scales::comma(round(baskets))} ({round(baskets_perc *100, 4)}%)"))) + 
      scale_x_continuous(labels = scales::percent) +
      scale_y_continuous(labels = scales::percent) + 
      labs(x = "Percent of Baskets", y = "Percent of Revenue Generated", 
           title = "Product Popularity", 
           caption = "Hover over the point to view product details") +  
      hrbrthemes::theme_ipsum(grid = FALSE), 
  tooltip = "text", 
)

# How many products are purchased per basket?
# confirms normally distributed data generation
grocery_basket <- 
  basket_db_funmart %>% 
    count(basket_id, name = "baskets") %>% 
    ungroup()

grocery_mean <- 
  grocery_basket %>% summarise(mean(baskets)) %>% purrr::pluck(1) %>% round(2)

grocery_sd <- 
  grocery_basket %>% summarise(sd(baskets)) %>% purrr::pluck(1) %>% round(2)

grocery_basket %>% 
  ggplot(aes(x = baskets)) + 
  geom_histogram(aes(y = stat(count)), 
                 colour = "grey", fill = blue_palette[4], bins = 21) + 
  geom_density(stat = "count", alpha = 0.3, 
               fill = blue_palette[4], colour = blue_palette[3], size = 0.7) + 
  #geom_rug() + 
  labs(x = "Products", y = "Baskets", 
       title = "Number of Products per Basket", 
       subtitle = stringr::str_glue("On average, there are {round(grocery_mean)} products/basket.
                                    95% of baskets contain {round(grocery_mean - grocery_sd * 2)} to {round(grocery_mean + grocery_sd * 2)} products.")) + 
  scale_x_continuous(breaks = seq(from = 0, to = max(grocery_basket$baskets), by = 2)) + 
  hrbrthemes::theme_ipsum(grid = FALSE)


# # Popular hours to place order
# order_db_funmart %>% 
#   count(hour = hour(order_time), name = "orders")
# 
# # Orders placed across quarters
# order_db_funmart %>% 
#   group_by(year = year(order_date)) %>% 
#   count(quarter = quarter(order_date), name = "orders")
# 
# # Popular times for orders (server load expectations)
# popular_order_time <- function(data = grocery, interval = c(month, weekday, hour)) {
#   data %>% 
#     .[, c("order_date", "order_time", "cost")] %>% 
#     transmute(month = month(order_date), 
#               weekday = wday(order_date), 
#               hour = hour(order_time), 
#               price = total_cost) %>% 
#     group_by({{ interval }}) %>% 
#     summarise(num_of_orders = n(), avg_price = mean(price)) %>% 
#     ungroup()
# }
# 
# grocery %>% 
#   popular_order_time(interval = weekday)

