##### 1: Load packages --------------------------------------------------------
# devtools::install_github("moamiristat/grocerycart")
library(grocerycart)
library(dplyr)
library(lubridate)
library(ggplot2)
library(arules)

##### 2: Load data ------------------------------------------------------------
# Availbale datasets in package
# data(package = "grocerycart")
# ?customer_db_funmart

# 4,996 customers
data("customer_db_funmart")

# 12,000 orders
data("order_db_funmart")

# 144,159 line items
data("basket_db_funmart")

# Grocery: join tables
grocery <- 
  basket_db_funmart %>% 
    group_by(basket_id, order_id) %>% 
    summarise(cost = sum(price)) %>% 
    ungroup() %>% 
    inner_join(order_db_funmart, by = "order_id") %>% 
    inner_join(customer_db_funmart, by = "customer_id")

##### 3: General analysis -----------------------------------------------------
# Order frequency (3 customers ordered 9 times)
grocery %>% 
  count(customer_id, name = "orders") %>% 
  count(orders, name = "freq")

# Average order value
grocery %>% 
  summarise(avg_price = mean(cost), num_orders = n(), 
            num_customers = n_distinct(customer_id))

# Create grocery buckets based on width or number of buckets
bucket_width <- 100
bucket_num <- 5
grocery_buckets <- function(width = NULL, n = NULL) {
  if(is.null(width) && is.null(n) || !is.null(width) && !is.null(n)) {
    cat(crayon::red("Specify exactly one of width and n\n"))
  }
  
  grocery %>% 
    group_by(customer_name) %>% 
    summarise(total_spent = sum(cost)) %>% 
    mutate(spent_bucket = cut_interval(total_spent, 
                                       length = width, 
                                       n = n, 
                                       right = "FALSE")) %>% 
    count(spent_bucket, name = "num_orders")
}

grocery_buckets(width = 100)

# Popular hours to place order
order_db_funmart %>% 
  count(hour = hour(order_time), name = "orders")

# Orders placed across quarters
order_db_funmart %>% 
  group_by(year = year(order_date)) %>% 
  count(quarter = quarter(order_date), name = "orders")

# Product distribution in baskets (draw average line)
basket_db_funmart %>% 
  count(product, name = "baskets") %>% 
  mutate(basket_perc = baskets / sum(baskets))

# Revenue generated by products (Nikai Air Fryer 3.2L generated 10% of revenue)
basket_db_funmart %>% 
  group_by(product) %>% 
  summarise(total_spent = sum(price)) %>% 
  mutate(spent_perc = total_spent / sum(total_spent)) %>% 
  arrange(desc(spent_perc))

# How many products are purchased per basket on average?
# confirms normally distributed data generation
basket_db_funmart %>% 
  count(basket_id, name = "baskets") %>% 
  ungroup() %>% 
  ggplot(aes(x = baskets)) + 
  geom_histogram(aes(y = stat(count)), colour = "grey", fill = "#7DB5D145", bins = 21) + 
  geom_density(stat = "count", alpha = 0.3, fill = '#7db5d1', colour = '#7db5d1', size = 0.7) + 
  geom_rug()

# Popular times for orders (server load expectations)
popular_order_time <- function(data = grocery, interval = c(month, weekday, hour)) {
  data %>% 
    .[, c("order_date", "order_time", "cost")] %>% 
    transmute(month = month(order_date), 
              weekday = wday(order_date), 
              hour = hour(order_time), 
              price = total_cost) %>% 
    group_by({{ interval }}) %>% 
    summarise(num_of_orders = n(), avg_price = mean(price)) %>% 
    ungroup()
}

grocery %>% 
  popular_order_time(interval = weekday)



